using System.ComponentModel;
using static BB2Replayer.Utils.Extensions;

namespace BB2Replayer.Replay.Types
{
	public enum BoardActionType
	{
		Move = 0,
		Block = 1,
		Blitz = 2,
		Pass = 3,
		[Label( "Hand-off" )] HandOff = 4,
		Foul = 5,
		[Label( "Knock-down" )] KnockDown = 6,
		[Label( "Kick-off" )] KickOff = 7,
		Bounce = 8,
		Catch = 9,
		[Label( "Touchdown" )] TouchDown = 10,
		[Label( "Stunned to Prone" )] StunnedToProne = 11,
		[Label( "KO recovery" )] KORecovery = 12,
		[Label( "Pick up" )] PickUpBall = 14,
		[Label( "Negative trait" )] NegaTrait = 15,
		[Label( "Landing" )] RightStuffLanding = 16,
		[Label( "Squirm Free From Always Hungry" )] AlwaysHungrySquirmFree = 17,
		Shadowing = 18,
		Stab = 19,
		Leap = 21,
		[Label( "Ball & Chain" )] BallAndChain = 23,
		Chainsaw = 25,
		[Label( "Multiple Block")] MultipleBlock = 26,
		[Label( "Hypnotic Gaze" )] HypnoticGaze = 27,
		[Label( "Pass Block")] PassBlock = 29,
		[Label( "Halfling Master Chef")] HalflingMasterChef = 30,
		Fireball = 31,
		[Label( "Fireball" )] FireballHit = 32,
		[Label( "Lightning Bolt" )] LightningBolt = 33,
		Referee = 34,
		[Label( "Landing" )] RightStuffLandingOnAnotherPlayer = 35,
		[Label( "Move player under ball" )] MovePlayerUnderBall = 37,
		[Label( "Dodge" )] DodgeFromDivingTackle = 39,
		[Label( "Multiple Block Stab" )] MultipleBlockStab = 41,
		[Label( "Activate player" )] ActivatePlayer = 42,
		[Label( "Number of fans" )] NumberOfFans = 46,
		Weather = 47,
		[Label( "Sweltering Heat" )] SwelteringHeat = 48,
		Feed = 49,
		[Label( "Bomb (direct hit)" )] BombDirectHit = 50,
		[Label( "Bomb (adjacent hit chance)" )] BombAdjacentHit = 51,
		[Label( "Throw a Bomb" )] ThrowABomb = 52,
		[Label( "Catch bomb" )] BombCatch = 53,
		[Label( "Bomb scatter" )] BombScatter = 54,
		[Label( "Bomb re-throw" )] BombReThrow = 55,
	};
}
