using System.ComponentModel;
using static BB2Replayer.Utils.Extensions;

namespace BB2Replayer.Replay.Types
{
	public enum RollType
	{
		None = 0,
		GFI = 1,
		Dodge = 2,
		[Label( "Armour Break" )] ArmourBreak = 3,
		Injury = 4,
		Block = 5,
		[Label( "Stand up with low MA" )]StandUpWithLowMA = 6,
		[Label( "Pick up ball" )] PickUpBall = 7,
		Casualty = 8,
		Catch = 9,
		Scatter = 10,
		ThrowIn = 11,
		Throw = 12,
		PushBack = 13,
		[Label( "Follow Up" )] FollowUp = 14,
		[Label( "Referee Ejection for fouling" )] RefereeFoulCheck = 15,
		Intercept = 16,
		[Label( "Recover from KO" )] KORecovery = 17,
		Touchback = 19,
		[Label( "Bone-head" )] BoneHead = 20,
		[Label( "Really Stupid" )] ReallyStupid = 21,
		[Label( "Wild Animal" )] WildAnimal = 22,
		Loner = 23,
		[Label( "Right Stuff landing" )] RightStuffLanding = 24,
		Regeneration = 25,
		[Label( "Thrown Team-Mate Scatter" )] ThrowTeamMateScatter = 26,
		[Label( "Always Hungry" )] AlwaysHungry = 27,
		[Label( "Squirm Free From Always Hungry" )] AlwaysHungrySquirmFree = 28,
		Dauntless = 29,
		[Label( "Safe Throw" )] SafeThrow = 30,
		[Label( "Jump Up Block" )] JumpUpBlock = 31,
		Shadowing = 32,
		Stab = 34,
		Leap = 36,
		[Label( "Foul Appearance" )] FoulAppearance = 37,
		Tentacles = 38,
		Chainsaw = 39,
		[Label( "Take Root" )] TakeRoot = 40,
		[Label( "Ball & Chain" )] BallAndChain = 41,
		[Label( "Hail Mary Pass")] HailMaryPass = 42,
		[Label( "Diving Tackle" )] DivingTackleUsed = 44, // NOTE: See Bad Bay vs Shadilay event 548-ish
		Pro = 45,
		[Label( "Hypnotic Gaze" )] HypnoticGaze = 46,
		Animosity = 49,
		[Label( "Blood Lust" )] BloodLust = 50,
		Feed = 51,
		Bribe = 52,
		[Label( "Halfling Master Chef" )] HalflingMasterChef = 53,
		[Label( "Fireball hit check" )] FireballHitCheck = 54,
		[Label( "Lightning Bolt hit check" )] LightningBoltHitCheck = 55,
		[Label( "Throw Team-Mate" )] ThrowTeamMate = 56,
		[Label( "Multiple Block")] MultipleBlock = 57,
		[Label( "Changing Weather - A Gentle Gust of Wind" )] GentleGustOfWind = 58,
		[Label( "Piling on (Armour)" )] PilingOnArmour = 59,
		[Label( "Piling on (Injury)" )] PilingOnInjury = 60,
		[Label( "Both Down block? Wrestle?" )] BothDownBlock = 61,
		StumbleDodge = 62,
		StandFirm = 63,
		Juggernaut = 64,
		StandFirmChainPush = 65,
		[Label( "Raise the Dead" )] RaiseTheDead = 66,
		[Label( "Number of Fans" )] NumberOfFans = 69,
		Weather = 70,
		[Label( "Sweltering Heat Check" )] SwelteringHeatCheck = 71,
		[Label( "Bomb adjacent explosion hit check" )] BombAdjacentHit = 72,
		[Label( "Chainsaw Armour Break Roll" )] ChainsawArmourBreak = 73,
	};
}
