from enum import Enum

class RollType(Enum):
    NoRoll = 0
    GFI = 1
    Dodge = 2
    ArmourBreak = 3
    Injury = 4
    Block = 5
    StandUpWithLowMA = 6
    PickUpBall = 7
    Casualty = 8
    Catch = 9
    Scatter = 10
    ThrowIn = 11
    Throw = 12
    PushBack = 13
    FollowUp = 14
    RefereeFoulCheck = 15
    Intercept = 16
    KORecovery = 17
    # ?? = 18
    Touchback = 19
    BoneHead = 20
    ReallyStupid = 21
    WildAnimal = 22
    Loner = 23
    RightStuffLanding = 24
    Regeneration = 25
    ThrowTeamMateScatter = 26
    AlwaysHungry = 27
    AlwaysHungrySquirmFree = 28
    Dauntless = 29
    SafeThrow = 30
    JumpUpBlock = 31
    Shadowing = 32
    # ?? = 33
    Stab = 34
    # ?? = 35
    Leap = 36
    FoulAppearance = 37
    Tentacles = 38
    Chainsaw = 39
    TakeRoot = 40
    BallAndChain = 41
    HailMaryPass = 42
    # ?? = 43
    DivingTackleUsed = 44
    Pro = 45
    HypnoticGaze = 46
    # ?? = 47
    # ?? = 48
    Animosity = 49
    BloodLust = 50
    Feed = 51
    Bribe = 52
    HalflingMasterChef = 53
    FireballHitCheck = 54
    LightningBoltHitCheck = 55
    ThrowTeamMate = 56
    MultipleBlock = 57
    GentleGustOfWind = 58
    PilingOnArmour = 59
    PilingOnInjury = 60
    BothDownBlock = 61
    StumbleDodge = 62
    StandFirm = 63
    Juggernaut = 64
    StandFirmChainPush = 65
    RaiseTheDead = 66
    # ?? = 67
    # ?? = 68
    NumberOfFans = 69
    Weather = 70
    SwelteringHeatCheck = 71
    BombAdjacentHit = 72
    ChainsawArmourBreak = 73